---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: calibre-secrets
  namespace: media
spec:
  encryptedData:
    calibre-ui-password: AgARopttyUbzXNQ+1amM7K9Ba8DovknELtwpYuxDWSHMLoqg2xTE10T7yL7Azk3kFtyxeeBukcf5qApvlWn5s9lwaNid5mOC1A0dL7fJqxmF2TzXgvrpQtOyLCK88UUyQ78fy+39BwxNZQYIMXfQvDSralx6NWJcDh6umH8dPlMm7di+P42a/tfAoc06nAIRnKqOCyODNpQxuJGGc/5HIbbHUmRKRk29So+KqH28Kogc9aKBo2coLwjc18znefoV/h+ixQtruu5c7Ee7nuceLLYsbZUnafC6zMhoKa6TYr9TR8PLGaLmc0Yw9jlkSidiLtUBd42YrrJU+Dg4N2+HnmyHOvhk/o65wOxXnu0uQ7an07aLA95YLnzmYErDXmg7CEuqsW1Ewxectal7Ihr4OFLy2uTs91rV7kf0o2y9Ag4jGbKaBNvliX3pXQCnhiN15jCtsUbAu7KyKpM7JUBS0a/rBFg43TZHFiGmju4VOW/B/4Ilm86mEmH6mxz3O9GzEV0VrtobV3ls7WApx6zFTKPAHpihh6iHVHYnJxVVC317yeQlLbsrzHPuaS4eWft0uw85iG1tLZX9o+wPuHSvVAKQ9DDmxPCZcGRbtXyrSStUX9uJkUSa4bYCeqP3nTZhfhyRTeGilx1HajF3r662tWf/0HppnEh3NLKam+MOFPFjjjDaXpDhPqKIzmyg25uBraFtVwK5Uvu5
    calibre-ui-username: AgAYYASwuvmLvPkYMBcmduqDS1Xb8lcSZ62BvDRhcicziD3T0yIPftYlxyvNmKjtb17WExWoyNw1J5VW2brsdWLW7RnE8Y+y2wJ8V3W+BvnEfk1mLUg/NmvEbiTewLGYnhBEVRTybg1gNkWPZiWoj5vt0Ws/yUYcUad0tfqaIhYp0t7Cx6O+Tt81p8L87BA/lb+LjL0oGnE+/be3eotf9TQfjCrex66FdMkLOV3JKrY7laLMk6MAvkKLXS8DrxEV20YkZiOrC7TwzfXZieburwDmn1DI4ZsQI293FwI/19GQmjM3J6wkd9dgxV+4/wL/hKQA6/7rqoq1YMdc0i3kFjlSnupq5HKMh9cdYINKWOQm6816mA8gGPu3+s69VNeZkSUonPG4brI++bH7YNW4jVWeG0thooMmpVL4X6P+WjcQE8ACBCjtUEB26NIqwY0w+g8859s13mbuUpf56L9zDK12/mN6Gqb8R4aK0Tpc+bY6g0K4HxnF6hLhMejYKOL2oTnBqo26AW52RCE1/8Bzx0Hi/eivw1NTK2SOO37QJBvpB2SB2dZYqsMwDSjKrPkfjSuZxiC8rulQptjI/9K0JDNAcZQ24hKNhdtOjY8vkJLQiWjxJixmTDehrmA631Cs8vWWyt70UJKBSKbYuMS5v0W2ZRiQZw61nygwjCsxwAM9zA1QN2o5WvziZ66wM/CiN9TeBdXI9X13
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: calibre-secrets
      namespace: media
    type: Opaque
